### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by geofbuck** [angeloxx/homebridge-vantage#1]
Tried to install from NPM but just kicks out error:

Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-vantage"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/sprint-fs
npm ERR! 404 
npm ERR! 404  'sprint-fs' is not in the npm registry.

Help?

**Comment by angeloxx** [comment]
I'm sorry, there're some mistakes that should be fixed. This week I plan to update the project and the package in the npm repository so please wait few days. I'll update this ticket when package installation works properly.

**Comment by angeloxx** [comment]
Last version of package (0.0.9) corrects that issue; in the next days I'll start again the development (currently paused to continue with homebridge-myhome project) and implement more functions.

**Comment by geofbuck** [comment]
Thanks so much! Can't wait to try it.

**Comment by geofbuck** [comment]
Hmm I can't find package 0.0.9. Where is it located?

**Comment by angeloxx** [comment]
npm will find it for you:
https://www.npmjs.com/package/homebridge-vantage

**Comment by elbugs** [comment]
Hello I'm trying to install too but I got this error, can you help me to solve it?
<img width="701" alt="captura de pantalla 2017-05-04 a las 17 58 06" src="https://cloud.githubusercontent.com/assets/3017280/25712981/6ffffec0-30f3-11e7-8f04-f9f0c2c1ba60.png"> I'm using latest Mac OS X. Thanks.

**Comment by angeloxx** [comment]
Retry with the lastest version AND please don't use a closed issue.

**Comment by elbugs** [comment]
Thanks for the update. I did it and now installs without problem. Before your reply I just deleted the dependency of sleep module in index.js and I got one load showing in the terminal but never was shown in the home app. Now, I'm in the same step. The system stops when it loads the first load, a DMX load. Could this kind of load be an issue? I'll test tomorrow to delete the DMX loads I have and try to run the plugin again and post an update. If meanwhile you have any idea, you can check the issue I opened few hours ago.
